"""Initial migration - users and models

Revision ID: a2073f0f28fb
Revises: 
Create Date: 2026-02-04 14:00:19.333005+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2073f0f28fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=False),
        sa.Column("avg_latency", sa.Float(), nullable=True),
        sa.Column("failure_rate", sa.Float(), nullable=True),
        sa.Column("cost_per_second", sa.Float(), nullable=True),
        sa.Column("total_requests", sa.Integer(), nullable=True),
        sa.Column("successful_requests", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_metrics_provider"),
        "provider_metrics",
        ["provider"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("FREE", "PRO", "ENTERPRISE", name="plantype"),
            nullable=False,
        ),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "influencer_models",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("VOICE", "FACE", "AVATAR", "STYLE", name="modeltype"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "TRAINING", "READY", "FAILED", name="modelstatus"
            ),
            nullable=True,
        ),
        sa.Column("training_data_url", sa.String(), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_influencer_models_user_id"),
        "influencer_models",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "generations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("VOICE", "IMAGE", "VIDEO", "TEXT", name="generationtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="generationstatus",
            ),
            nullable=True,
        ),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=True),
        sa.Column("latency", sa.Float(), nullable=True),
        sa.Column("output_url", sa.String(), nullable=True),
        sa.Column("input_data", sa.JSON(), nullable=True),
        sa.Column("output_metadata", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["influencer_models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generations_model_id"),
        "generations",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generations_user_id"),
        "generations",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generations_user_id"), table_name="generations")
    op.drop_index(op.f("ix_generations_model_id"), table_name="generations")
    op.drop_table("generations")
    op.drop_index(
        op.f("ix_influencer_models_user_id"), table_name="influencer_models"
    )
    op.drop_table("influencer_models")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_provider_metrics_provider"), table_name="provider_metrics"
    )
    op.drop_table("provider_metrics")
    # ### end Alembic commands ###
